### ISSUE TITLE
Cryptic KeyError when Renaming Material in Term.new() Causes Evaluation Failure

### ISSUE THREAD

**Issue by aaronksolomon** [sfepy/sfepy#1146] opened 2024-09-08 01:00 UTC
#### **Description**
Solve a problem based on the its2D interactive example https://sfepy.org/doc-devel/primer.html  (file: sfepy/examples/linear_elasticity/its2D_interactive.py) got an error when changing the name of the material in the `Term.new()` function. Specifically, changing the material name e.g., `My_material`, to `mat` resulted in the following error when running `pb.solve()`:

```python
KeyError: (‘Omega’, 2)
```

#### Here is the working version:

```python
material = Material('My_material', D=D)

t1 = Term.new('dw_lin_elastic(My_material.D, v, u)',
                integral, omega, My_material=material, v=v, u=u)
```

#### Non-working version:

```python
mat = Material('My_material', D=D)
...
t1 = Term.new('dw_lin_elastic(mat.D, v, u)',
                integral, omega, mat=mat, v=v, u=u)
```
      
Changing the name from `My_material` to `mat` in the `Term.new()` call results in a key access error deep in the evaluation loop. The issue seems related to the region and material namespace conventions. There is no error handling.

#### **Immediate Concern**
The cryptic nature of this error makes it difficult to diagnose. The material name appears to be arbitrary in other use cases.

Proposed:
1. Catch this error earlier with some error handling.
2. Indicate specific naming constraints in using the `term.new()` functionality, and make clear how material assignment works more explicitly.

#### **Larger Concerns**
Through debugging, I have identified several broader issues with the SfePy package that could benefit from improvement:
1. **Error Reporting**: Error messages are sometimes cryptic and do not provide actionable guidance. Better error handling with specific feedback and pointers to documentation regarding usage and naming conventions would improve user experience significantly.
   
2. **Documentation**: The documentation does not adequately explain much of the complex functionality of the software, but instead relies almost entirely on examples. This makes learning the software extremely time-consuming and frustrating—as a user is forced to employ a trial-and-error approach to coding. All functions, classes, and modules should ideally have clear and concrete explanations of syntax and usage with specific examples of typical, as well as advanced usage. Clearer, more detailed documentation on actual function methodology and usage, overall organization of the modules, and operation of the code would save users from a lot of trial and error.

3. **Design Complexity**: The design of the package appears quite complex, especially in areas like defining materials and applying terms. If such complexity is necessary for optimal use, it perhaps could be balanced with clear and detailed explanations of how this complexity is leveraged into functional processing in the operation of the system. Explaining more clearly and in more precise detail how the system is designed to work with FEMs would make the package more accessible and easier to use for those not familiar with the internal workings.

#### **Suggested Action**
- Provide better error handling and user feedback for materials, regions, terms, or other naming misconfigurations.
- Add clear documentation on any specific rules for functions, especially critical ones such as `Term.new()` and improve explanations of how materials, regions, boundaries (to name just a few components), and the solver are expected to interact.

Thank you for your consideration and for maintaining SfePy. It seems to be a powerful system, that is unfortunately fairly inaccessible through the documentation provided. I believe addressing these issues could make the package more robust and user-friendly, and ultimately more accessible to a wider community.

---

### **Environment:**
- SfePy version: 2024.2
- Python version: 3.12
- Platform: macOS / Anaconda environment

**Comment by rc** [comment] 2024-09-09 09:39
Hi, thanks for your feedback! It is true that the error message is not helpful and should be fixed. In the mean time let me explain the cause of the error:

> #### Non-working version:
> 
> ```python
> mat = Material('My_material', D=D)
> ...
> t1 = Term.new('dw_lin_elastic(mat.D, v, u)',
>                 integral, omega, mat=mat, v=v, u=u)
> ```

The material variable is called `mat` in the Python's namespace, but that is not the name that should be used in the equations. There you need to use the name of the material (`mat.name`), which in this case is `'My_material'`, i.e. the first argument of the `Material()` constructor. - this name should be used both in the string with the term definition and the assignment of the keyword arguments in the `Term.new()` call. BTW. the same holds for the `u`, `v` arguments.

Let me know if that is understandable.

Concerning the documentation, we improve it as time and limited man-power permits (PRs welcome etc.).

**Comment by rc** [comment] 2024-09-24 10:07
FYI: I have tried to address this issue in #1149.

**Comment by aaronksolomon** [comment] 2024-09-24 17:28
Thanks Robert!

Appreciate you taking my thoughts Into consideration.

I haven’t had a chance to use the software too much more, but happy to
contribute any docs I come up with that may be helpful, especially for a
first time user who is learning it off the web.

🙏🏻
Aaron Solomon (he/him)
*Mindfulness Teacher and Counselor*
*AMGA Single Pitch Climbing Instructor*
*Integrated Mindfulness <https://aaronsolomon.me/>*
*Somatic Experiencing*
*Nonviolent communication*
*Schedule a time to connect <https://calendly.com/brotherman/connect>*
*845.219.9599*

**Closed** 2024-09-29 18:54 UTC
