### ISSUE TITLE
Mooney-Rivlin Interactive mode

### ISSUE THREAD

**Issue by brike105** [sfepy/sfepy#672] opened 2021-03-10 11:24 UTC
Hello everyone,

I am working on 3D FE for my master thesis and i need to simulate liver movement. I want to run the nearly imcompressible Mooney-Rivlin hyperelastic Model, and for that I do test on 3D cube mesh first. I work in interactive mode (with Jupyter notebooks). Problem is : my code run for equations balanced with linear elasticity, but crash when I try to implement Mooney-Rivlin equations. Does anyone have an idea of what is wrong with my code ? 

Thank you in advance, Brieuc

I attached the notebook and the mesh in a .zip file here. 
[Mooney-Rivlin BRIEUC.zip](https://github.com/sfepy/sfepy/files/6115383/Mooney-Rivlin.BRIEUC.zip)

And this is my error script : 
sfepy: reading mesh (/Users/brieuceverard/opt/anaconda3/pkgs/sfepy-2020.4-py38hc7193ba_1/lib/python3.8/site-packages/sfepy/meshes/3d/cube_medium_tetra.mesh)...
sfepy:   number of vertices: 448
sfepy:   number of cells:
sfepy:     3_4: 1782
sfepy: ...done in 0.01 s
sfepy: saving regions as groups...
sfepy:   Omega
sfepy:   faceDown
sfepy:   faceUp
sfepy: ...done
sfepy: reading mesh (regions.vtk)...
sfepy:   number of vertices: 448
sfepy:   number of cells:
sfepy:     3_4: 1782
sfepy: ...done in 0.00 s
sfepy: point scalars Omega at [-1.6 -0.5  0. ]
sfepy: range: 1.00e+00 1.00e+00 l2 norm range: 1.00e+00 1.00e+00
sfepy: point scalars faceDown at [-0.5 -0.5  0. ]
sfepy: range: 0.00e+00 1.00e+00 l2 norm range: 0.00e+00 1.00e+00
sfepy: point scalars faceUp at [ 0.6 -0.5  0. ]
sfepy: range: 0.00e+00 1.00e+00 l2 norm range: 0.00e+00 1.00e+00
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.00 s
sfepy: matrix shape: (8014, 8014)
sfepy: assembling matrix graph...
sfepy: ...done in 0.09 s
sfepy: matrix structural nonzeros: 588998 (9.17e-03% fill)
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
sfepy:     mat
sfepy: ...done in 0.00 s
sfepy: giving up!
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-2d10dee3b01b> in <module>
    119 pb.set_solver(nls)
    120 status = IndexedStruct()
--> 121 vec = pb.solve(status=status)
    122 print('Nonlinear solver status:\n', nls_status)
    123 print('Stationary solver status:\n', status)

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/discrete/problem.py in solve(self, state0, status, force_values, var_data, update_bcs, update_materials, save_results, step_hook, post_process_hook, post_process_hook_final, verbose)
   1429                 step_hook=step_hook, post_process_hook=post_process_hook)
   1430 
-> 1431             vec = tss(state0.get_vec(self.active_only),
   1432                       init_fun=init_fun,
   1433                       prestep_fun=prestep_fun,

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/solvers/ts_solvers.py in _standard_ts_call(self, vec0, nls, init_fun, prestep_fun, poststep_fun, status, **kwargs)
     30         poststep_fun = get_default(poststep_fun, lambda ts, vec: None)
     31 
---> 32         result = call(self, vec0=vec0, nls=nls, init_fun=init_fun,
     33                       prestep_fun=prestep_fun, poststep_fun=poststep_fun,
     34                       status=status, **kwargs)

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/solvers/ts_solvers.py in __call__(self, vec0, nls, init_fun, prestep_fun, poststep_fun, status, **kwargs)
     71         prestep_fun(ts, vec0)
     72 
---> 73         vec = nls(vec0)
     74 
     75         poststep_fun(ts, vec)

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/solvers/nls.py in __call__(self, vec_x0, conf, fun, fun_grad, lin_solver, iter_hook, status)
    255 
    256                 try:
--> 257                     vec_r = fun(vec_x)
    258 
    259                 except ValueError:

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/discrete/evaluate.py in eval_residual(self, vec, is_full)
     71             vec = self.make_full_vec(vec)
     72 
---> 73         vec_r = self.problem.equations.eval_residuals(vec)
     74         if self.matrix_hook is not None:
     75             vec_r = self.matrix_hook(vec_r, self.problem, call_mode='residual')

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/discrete/equations.py in eval_residuals(self, state, by_blocks, names)
    700             out = self.create_stripped_state_vector()
    701 
--> 702             self.evaluate(mode='weak', dw_mode='vector', asm_obj=out)
    703 
    704         return out

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/discrete/equations.py in evaluate(self, names, mode, dw_mode, term_mode, asm_obj)
    632             extras = []
    633             for eq in eqs:
--> 634                 out = eq.evaluate(mode=mode, dw_mode=dw_mode,
    635                                   term_mode=term_mode, asm_obj=asm_obj)
    636                 if isinstance(out, tuple): extras.extend(out[1])

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/discrete/equations.py in evaluate(self, mode, dw_mode, term_mode, asm_obj)
    849 
    850                 for term in self.terms:
--> 851                     val, iels, status = term.evaluate(mode=mode,
    852                                                       term_mode=term_mode,
    853                                                       standalone=False,

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/terms/terms.py in evaluate(self, mode, diff_var, standalone, ret_status, **kwargs)
   1454             else:
   1455                 _args = tuple(args) + (mode, term_mode, diff_var)
-> 1456                 fargs = self.call_get_fargs(_args, kwargs)
   1457 
   1458                 if varr.dtype == nm.float64:

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/terms/terms.py in call_get_fargs(self, args, kwargs)
   1290     def call_get_fargs(self, args, kwargs):
   1291         try:
-> 1292             fargs = self.get_fargs(*args, **kwargs)
   1293 
   1294         except (RuntimeError, ValueError):

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/terms/terms_hyperelastic_base.py in get_fargs(self, mat, virtual, state, mode, term_mode, diff_var, **kwargs)
    146 
    147         name = state.name
--> 148         fd = self.get_family_data(state, self.region, self.integral,
    149                                   self.geometry_types[name],
    150                                   self.arg_steps[name],

~/opt/anaconda3/lib/python3.8/site-packages/sfepy/terms/terms_hyperelastic_base.py in __call__(self, state, region, integral, integration, step, derivative)
     69             fargs = fargs + (vec, vg, state.field.econn)
     70 
---> 71             self.family_function(*fargs)
     72             cache[data_key] = data
     73 

sfepy/terms/extmods/terms.pyx in sfepy.terms.extmods.terms.dq_finite_strain_tl()

ValueError: ccore error (see above)

**Comment by rc** [comment] 2021-03-11 13:36
Hello Brieuc,

the problem is caused by a too large initial displacement in your Dirichlet boundary condition - try using
```
shift_u = EssentialBC('shift_u', faceUp, {'u.0' : 0.01})
```
and also change
```
nls = Newton({'i_max' : 10}, lin_solver=ls, status=nls_status)
```
as the solver will not converge in a single iteration.

Explanation: the nonlinear terms check that element volumes stay positive. If the initial deformation is too large (elemen(s) are "warped"), there is no automatic recovery possible, unlike in subsequent nonlinear solver iterations, where the step size can be reduced. So you need to apply the initial deformation "small enough", and then increase it gradually to the target value. Have a look at e.g. [this example](http://sfepy.org/doc/examples/large_deformation-gen_yeoh_tl_up_interactive.html), lines 317-320 to see how to apply time-dependent BCs in the interactive mode.

BTW. running the code as a Python script actually shows the error message from the C module. It is not visible in the notebook for some reason.

**Comment by brike105** [comment] 2021-03-13 10:08
Thank you for your answer, it works, it is exactly what i needed. I also tried the time-step-dependent BC, and by adding a large number of intermediate time steps i could reach the bigger displacement value I wanted. I will be able to move forward with my project now. 

Thank you !
Brieuc

**Comment by rc** [comment] 2021-03-13 15:19
Hth, I am closing this, but feel free to ask more.

**Closed by rc** 2021-03-13 15:19 UTC
Labels: question
