### ISSUE TITLE
Term dw_surface_dot missing

### ISSUE THREAD

**Issue by piftouf** [sfepy/sfepy#802] opened 2022-04-06 09:33 UTC
Hello, my code working on the version Sfepy 2020.3 does not work on the version 2022. It seems the equation term "dw_surface_dot" disappears, do you know why?

**Comment by rc** [comment] 2022-04-06 09:42
There is now just `dw_dot` for both surface and volume integrals.

**Comment by piftouf** [comment] 2022-04-06 12:14
Thank you for the help. dw_dot is not recognized, if I run my code with Sfepy 2022.1.

**Comment by rc** [comment] 2022-04-08 09:38
This is strange - can you attach a complete minimal example that  demonstrates the problem?

**Comment by piftouf** [comment] 2023-02-17 14:44
Hi, sorry for the delay. Here is an exemple that works with (Sfepy 2020.3 et Meshio 4.4.6) and not with higher versions of Sfepy even if I replace "dw_surface_dot" by "dw_dot" (the t2 term in the code):

import numpy as nm
from sfepy.solvers.ls import ScipyDirect
from sfepy.base.base import assert_, output, ordered_iteritems, IndexedStruct
from sfepy.discrete.fem import Mesh, FEDomain, Field
from sfepy.discrete import (FieldVariable, Material, Integral, Integrals,
                            Equation, Equations, Problem, Function)
from sfepy.solvers.nls import Newton
from sfepy.solvers.ts_solvers import SimpleTimeSteppingSolver
from sfepy.discrete.conditions import Conditions, EssentialBC, InitialCondition
from sfepy.terms import Term

n_nod =101 #number of spatial points
timeNbPoints =102 #number of temporal points
timeWindows=50

epsilon =1E-6

w = 10
Rb=1
D=10
g=3
s=100

def mesh_hook_One_Layer(mode):
    """
    Generate the 1D mesh.
    """
    if mode == 'read':
        x = nm.linspace(0.0, w, n_nod).reshape((n_nod, 1))
                
        conn = nm.arange(n_nod, dtype=nm.int64).repeat(2)[1:-1].reshape((-1, 2))
        mat_ids = nm.zeros(n_nod - 1, dtype=nm.int64)
        descs = ['1_2']
                      
        mesh = Mesh.from_data('time', x, None, [conn], [mat_ids], descs)#it is not a mesh of the time!
        return mesh

    elif mode == 'write':
        pass    

def get_ic(coors, ic): #pulsed excitation

    x = coors[:, 0]
    return nm.where( x<Rb ,1,0)    

def main():
    mesh = mesh_hook_One_Layer(mode='read')
    domain = FEDomain('cross_section', mesh)          
    Omega=domain.create_region('Omega', 'all')   
    Gamma_Left=domain.create_region('Gamma_Left', 'vertices in (x < %f)'%(epsilon), 'vertex')  
    Gamma_Right=domain.create_region('Gamma_Right', 'vertices in (x > %f)'%(w-epsilon), 'vertex')
    
    field = Field.from_args('field', nm.float64, 'scalar', Omega,approx_order=1)   
    u = FieldVariable('u', 'unknown', field, history=1)
    v = FieldVariable('v', 'test', field, primary_var_name='u')    

    m_layer = Material('m_layer', D=D, g=g, s=s)
    
    integral1 = Integral('i', order=1)
  
    t1 = Term.new('dw_volume_dot(v, du/dt)', integral1, Omega, v=v, u=u)

    t2 = Term.new('dw_surface_dot(m_layer.s, v, u)', integral1, Gamma_Left, m_layer=m_layer, v=v, u=u)    
    # t2 = Term.new('dw_dot(m_layer.s, v, u)', integral1, Gamma_Left, m_layer=m_layer, v=v, u=u)
    
    t3 = Term.new('dw_volume_dot(m_layer.g, v, u)', integral1, Omega,m_layer=m_layer, v=v, u=u)
    t4 = Term.new('dw_laplace(m_layer.D, v, u)', integral1, Omega, m_layer=m_layer, v=v, u=u)
    t5 = Term.new('dw_surface_dot(m_layer.s, v, u)', integral1, Gamma_Right, m_layer=m_layer, v=v, u=u)

    EqPopFreeExciton = Equation('EqPopFreeExciton', t1 + t2 + t3 + t4 + t5)
    eqs = Equations([EqPopFreeExciton])  
    pb = Problem('cross_section', equations=eqs)
    
    ls = ScipyDirect({})
    nls_status = IndexedStruct()
    
    pb.set_output_dir('./outFolder/')

    ic_fun = Function('ic_fun', get_ic)
    ic = InitialCondition('ic', Omega, {'u.0' : ic_fun})    
    pb.set_ics(Conditions([ic]))
    nls = Newton({},i_max=1, eps_a= 1e-10, lin_solver=ls, status=nls_status)
    tss = SimpleTimeSteppingSolver({'t0' : 0.0, 't1' : timeWindows, 'dt' : None,'n_step' : timeNbPoints},
                                   nls=nls, context=pb, verbose=False)
    pb.set_solver(tss)    
    # state  = pb.solve(step_hook=step_hook_One_Pop)
    state  = pb.solve()
    output(nls_status) 
    
if __name__ == '__main__':
    main()

**Comment by rc** [comment] 2023-02-22 10:03
The problem is not in the term but in the region definition. I will update the code to give a more meaningful error message. The fix is simple, use:
```
    Gamma_Left = domain.create_region('Gamma_Left', 'vertices in (x < %f)'%(epsilon), 'facet')
    Gamma_Right = domain.create_region('Gamma_Right', 'vertices in (x > %f)'%(w-epsilon), 'facet')
```
i.e. `facet` kind instead of `vertex`.

**Comment by rc** [comment] 2023-02-22 10:11
Actually as your domain is 1D `vertex` should work as well. I will fix that too.

**Comment by rc** [comment] 2023-02-22 12:17
WIth the git version, your script should work without modifications. I am closing this, but feel free to ask more, if needed.

**Closed by rc** 2023-02-22 12:17 UTC

**Comment by piftouf** [comment] 2023-03-02 14:01
It works, thank a lot!
