### ISSUE TITLE
SfePy Primer example showing different results - Ipython f value calc. error

### ISSUE THREAD

**Issue by imselva** [sfepy/sfepy#629] opened 2020-07-21 11:06 UTC
When I run the Primer example in Pycharm,

python ./simple.py its2D_1.py
python ./postproc.py its2D.vtk

The result obtained is the same as shown in the documentation. 

But after running python ./simple.py its2D_2.py
python ./postproc.py its2D.vtk -b

The resulting stress and strain I am getting is different from the one in the SfePy documentation. 
![primer_deviation](https://user-images.githubusercontent.com/68395200/88047293-b3f21e00-cb51-11ea-8ce6-a8ec35ba9e88.JPG)

Also while using Ipython,

Until the calculation of K value everything works well,
but during the calculation of f value, I am getting the following results:

In [15]: f = pb.evaluator.eval_residual(u)
    ...: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-f6336ad750e0> in <module>
----> 1 f = pb.evaluator.eval_residual(u)

~\Downloads\sfepy-master\sfepy-master\sfepy\discrete\evaluate.py in eval_residual(self, vec, is_full)
     69     def eval_residual(self, vec, is_full=False):
     70         if not is_full and self.problem.active_only:
---> 71             vec = self.make_full_vec(vec)
     72
     73         vec_r = self.problem.equations.eval_residuals(vec)

~\Downloads\sfepy-master\sfepy-master\sfepy\discrete\evaluate.py in make_full_vec(self, vec)
    119
    120     def make_full_vec(self, vec):
--> 121         return self.problem.equations.make_full_vec(vec)
    122
    123 def create_evaluable(expression, fields, materials, variables, integrals,

~\Downloads\sfepy-master\sfepy-master\sfepy\discrete\equations.py in make_full_vec(self, svec, force_value)
    528         vector.
    529         """
--> 530         return self.variables.make_full_vec(svec, force_value)
    531
    532     def set_variables_from_state(self, vec, step=0):

~\Downloads\sfepy-master\sfepy-master\sfepy\discrete\variables.py in make_full_vec(self, svec, force_value, vec)
    574             indx = self.di.indx[var.name]
    575             aindx = self.adi.indx[var.name]
--> 576             var.get_full(svec, aindx.start, force_value, vec, indx.start)
    577
    578         return vec

~\Downloads\sfepy-master\sfepy-master\sfepy\discrete\variables.py in get_full(self, r_vec, r_offset, force_value, vec, offset)
   1714
   1715         # Reduced vector values.
-> 1716         vec[eq_map.eqi] = r_vec
   1717
   1718         # EPBC.

ValueError: shape mismatch: value array of shape (55,2) could not be broadcast to indexing result of shape (110,)

I don't know where this is going wrong,

I am new to SfePy, I want to learn the basics asap, but I am facing so many issues. 
It would be really nice if someone could help me resolve this issue.

Thank you in advance

Yours faithfully,
Selva

**Comment by rc** [comment] 2020-07-24 11:19
Hi Selva,

it seems that the problem is in the step 6 (changing the u vector shape) - try restoring the shape by `u = u.ravel() `. Thanks for reporting the problem, it could be fixed by replacing the step 3 with:
```
In [3]: u = state().copy()
```

**Closed** 2022-09-22 06:56 UTC
Labels: defect, docs
